import { AUTH } from "@/constants";
import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: `${AUTH.firstname} | Full Stack Portfolio`,
  description: "Welcome to my full stack Next.js 14 space portfolio.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "full-stack",
    "developer",
    `${AUTH.firstname.toLowerCase()}`,
    `${AUTH.lastname.toLocaleLowerCase()}`,
    `${AUTH.fullname.toLowerCase()}`,
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: `${AUTH.fullname}`,
    url: `https://github.com/${AUTH.github}/`,
  },
} as const;
